apiVersion: skaffold/v1beta6
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - image: spring-petclinic-customers-service
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          SERVICE_NAME: spring-petclinic-customers-service
          SERVICE_VERSION: '{{.VERSION}}'
    - image: spring-petclinic-vets-service
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          SERVICE_NAME: spring-petclinic-vets-service
          SERVICE_VERSION: '{{.VERSION}}'
    - image: spring-petclinic-visits-service
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          SERVICE_NAME: spring-petclinic-visits-service
          SERVICE_VERSION: '{{.VERSION}}'
    - image: spring-petclinic-api-gateway
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          SERVICE_NAME: spring-petclinic-api-gateway
          SERVICE_VERSION: '{{.VERSION}}'
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/spbkelt/{{.IMAGE_NAME}}:{{.VERSION}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: spring-petclinic-customers-service
        chartPath: charts/spring-petclinic-gcp/charts/spring-petclinic-customers-service
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/spbkelt/{{.IMAGE_NAME}}'
          image.tag: '{{.VERSION}}'
      - name: spring-petclinic-vets-service
        chartPath: charts/spring-petclinic-gcp/charts/spring-petclinic-vets-service
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/spbkelt/{{.IMAGE_NAME}}'
          image.tag: '{{.VERSION}}'
      - name: spring-petclinic-visits-service
        chartPath: charts/spring-petclinic-gcp/charts/spring-petclinic-visits-service
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/spbkelt/{{.IMAGE_NAME}}'
          image.tag: '{{.VERSION}}'
      - name: spring-petclinic-api-gateway
        chartPath: charts/spring-petclinic-gcp/charts/spring-petclinic-api-gateway
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/spbkelt/{{.IMAGE_NAME}}'
          image.tag: '{{.VERSION}}'
