# !! File must end with empty line !!
dependencies:
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: spring-petclinic-gcp
  repository: file://../spring-petclinic-gcp
