dependencies:
- name: spring-petclinic-visits-service
  version: "0.1.0-SNAPSHOT"
  repository: "http://jenkins-x-chartmuseum:8080"
- name: spring-petclinic-vets-service
  version: "0.1.0-SNAPSHOT"
  repository: "http://jenkins-x-chartmuseum:8080"
- name: spring-petclinic-customers-service
  version: "0.1.0-SNAPSHOT"
  repository: "http://jenkins-x-chartmuseum:8080"
